### ISSUE TITLE
Matching van de url's in de scenario cases is niet strict genoeg

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#101]
# Bug
De laatste call (GET https://..../zaken/results) wordt onterecht in de rapportage opgenomen
![image](https://user-images.githubusercontent.com/37145898/54766352-6bdc8780-4bfb-11e9-8475-d09b080430c9.png)

![image](https://user-images.githubusercontent.com/37145898/54766784-35533c80-4bfc-11e9-8363-575f5df2047a.png)

**Comment by alextreme** [comment]
Dit is doorgevoerd naar vng-test. Wordt maandag a.s. uitgerold naar vng-staging
