### ISSUE TITLE
PATCH-request wordt niet goed verwerkt door de testvoorziening

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#103]
# Bug

Als we kijken naar deze PATCH-request (https://vng-staging.maykin.nl/696/log/2378) die ik via de ATV heb laten verlopen dan zien we dat de tekst van de quote niet vervangen is.

![afbeelding](https://user-images.githubusercontent.com/37145898/55251240-56e1a300-5250-11e9-93a5-8ec7b51017ed.png)

Echter als we dezelfde request direct op de gehoste versie uitvoeren dan gaat het wel goed.

```
PATCH /demo-api/api/v2/quotes/b2b96c56-b4e9-43b4-87a5-095c9e23b35c HTTP/1.1
Host: ref.tst.vng.cloud
Content-Type: application/json
cache-control: no-cache
Postman-Token: bd2e8789-7849-44fd-a864-38465b18c315
{
	"tekst": "Deze quote gedeeltelijk vervangen"
}------WebKitFormBoundary7MA4YWxkTrZu0gW--
```
Response:
```
{
    "url": "http://ref.tst.vng.cloud/demo-api/api/v2/quotes/b2b96c56-b4e9-43b4-87a5-095c9e23b35c",
    "tekst": "Deze quote gedeeltelijk vervangen",
    "bronNaam": "Shakespeare 2",
    "bronLink": "http://citation.org",
    "aangemaakt": "2019-03-29T17:08:39.152089Z",
    "laatstBijgewerkt": "2019-03-29T17:23:33.087007Z"
}
```

**Comment by AlviseSembenico** [comment]
I struggling getting the same result because if I simulate the same call I get the correct result below. Could you please try again and see if you still get the result.
![postamn](https://user-images.githubusercontent.com/28757412/55320673-f6cd4580-5477-11e9-8e28-6a1dd3bb2537.png)

Nonetheless, the page displays the raw response's body, before the rewriting.

**Comment by AlviseSembenico** [comment]
Fixed in commit https://github.com/maykinmedia/api-testvoorziening/commit/4acc16c50a58e58a6a268dabc82cc03cab281f5b

**Comment by alextreme** [comment]
Oplossing beschikbaar op vng-staging, ter review

**Comment by HenriKorver** [comment]
The PATCH request is now properly processed but returns a 500 error in Postman. In the log of the test platform it gives a 200. The same problemfor the PUT-request. See below.
![afbeelding](https://user-images.githubusercontent.com/37145898/55832347-ac9e3100-5b15-11e9-9df5-b7b22a3bf0d8.png)

The PATCH and POST request are not updated in the report
![afbeelding](https://user-images.githubusercontent.com/37145898/55832408-cd668680-5b15-11e9-8c0a-839c6f020aa4.png)

**Comment by HenriKorver** [comment]
Most of the problems mentioned in the post above occurred after I added a scenario case for PATCH.

![afbeelding](https://user-images.githubusercontent.com/37145898/55834162-88445380-5b19-11e9-8901-a47984543fa0.png)

**Comment by alextreme** [comment]
@AlviseSembenico This might be a problem with the Demo API instead. I'll add a Sentry link in Taiga for you

**Comment by AlviseSembenico** [comment]
Fixed in df3d44e1c29b5b08a17f0aa4d2f0bd14fba73b92

**Comment by alextreme** [comment]
Here we go, now it works as expected for me on vng-staging:

![Screenshot_2019-04-11_17-25-37](https://user-images.githubusercontent.com/226839/55969913-e2125e00-5c7e-11e9-97aa-aaf66b6f9d7d.png)

And the postman collection I used:

[Demo API PUT-PATCH-DELETE.postman_collection.txt](https://github.com/VNG-Realisatie/api-testvoorziening/files/3069392/Demo.API.PUT-PATCH-DELETE.postman_collection.txt)

We have found an error with the Docker version of the Demo API that Alvise is working on, however the hosted version worked for me without problems.

**Comment by HenriKorver** [comment]
Yes on the hosted version it works now, but in the docker version the url returned after a POST-call misses a slash after `maykin.nl` (see below). Is this a uri-rewite problem?

```
{
    "url": "https://155506251661-vng-staging.maykin.nlapi/v2/quotes/c1d0bd67-4ad7-46ea-94bd-7f8c950a073a",
    "tekst": "To be or to be",
    "bronNaam": "Shakespeare 3",
    "bronLink": "http://citation.org",
    "aangemaakt": "2019-04-12T09:53:03.764352Z",
    "laatstBijgewerkt": null
}
```

**Comment by AlviseSembenico** [comment]
@HenriKorver we are aware of it, I am currently working on it.

**Comment by HenriKorver** [comment]
Great! However this is a different problem than the patch-problem. Therefore I added a separate issue for it: #122. The PATCH issue is solved and can be closed
