### ISSUE TITLE
As a demonstrator I want to be able to recover a mistake during  a client test session

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#104]
such that it is easier to teach people how the test platform works

**Toelichting**:
It is important that we have implemented this feature before the API LAB

**Oplossingsrichting**:
Add a flag (demonstration mode) to the admin module. If the flag is set than the report shows a green box when the request has succeeded the last time. At the moment if a request failed it is impossible to recover and the red box will stay forever.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
It would be nice to have to checkbox directly in de user interface of the test platform (not in de admin)

**Comment by alextreme** [comment]
This has now been implemented, deployed and verified against the hosted Demo API session by deliberately making a mistake with POST fields.

With the sandbox-checkbox enabled the last status will be used. So if you make a mistake you'll get a red block in the report, but if you correct your POST it will become green. If you make the same mistake again it will switch back to red.
