### ISSUE TITLE
Formuleren van vragen voor Mentimeter onderzoek tijdens API Lab

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#106]
# Scrumtaak

Zie www.menti.com (code: 812181) voor enquête ZGW API.

Voorbeeld enquête voor testvoorziening:

* Wat weerhoudt je om de testvoorziening te gaan gebruiken?
* Ben je van plan om de testvoorziening te integreren in je eigen ontwikkelstraat?
* Welke user stories mis je?
* Wat vind je het belangrijkst:
  * Dat zowel consumers als providers getest kunnen worden
  * Dat voornamelijk API providers  kunnen worden getest
  * Dat voornamelijk consumer-applicaties kunnen worden getest.
* Vind je het belangrijk dat de compliancy van je applicatie formeel kan worden aangetoond door middel van een fysiek rapport?
* Wanneer ga je je applicatie voorzien van een badge? 
  * Alleen als je applicatie volledig compliant is
  * Altijd zodat iedereen kan zien hoe volwassen de applicatie is
  * Alleen als je applicatie een redelijke mate van compliancy heeft bereikt.
  * Nooit
* Welke belangrijke functionaliteit/feature mist de testvoorziening?
* Wat is je belangrijkste drijfveer om de testvoorziening te gaan gebruiken?
* De testvoorziening is gebaseerd op Postman voor het invoeren van testscripts. Is dat een goed keuze?
* Ben je van plan zelf Postman scripts te schrijven en in te voeren op de testvoorziening?

**Comment by HenriKorver** [comment]
@alextreme @JanWillemKooi Graag feedback en aanvulling!

**Comment by TCIMEddy** [comment]
@HenriKorver Ik zet deze vragen in een mentimeter (en zal de code in dit kanaal zetten). En zal de feedback in dit kanaal verwerken. Ik zou de vragen wel maximeren tot een stuk of 7 maar dat is aan jou!

**Comment by JanWillemKooi** [comment]
Wil je alleen multiplechoicevragen of ook openvragen? Of bij meerkeuze de mogelijkheid met -Anders namelijk .... waarbij mensen zelf iets kunnen inschieten.
Ben het eens met Eddy om niet te veel vragen te stellen.

**Comment by JanWillemKooi** [comment]
Wat is je doel van de enquete en voor wie is het bedoeld? Zullen we morgen dit even bespreken?

**Comment by Hugo-ter-Doest** [comment]
Het doel van de enquete is om te achterhalen wat er nodig is om een RC uit te brengen. Wat mist er nog, wat moet er iig in zitten, etc.

**Comment by TCIMEddy** [comment]
@HenriKorver 1e concept gemaakt. Beetje veel vragen en wellicht is het verstandig om een gedeelte plenair te doen en een gedeelte als huiswerk. Presenteer jezelf of moet ik dat doen? Bijgevoegd menti
![Schermafbeelding 2019-04-08 om 10 01 26](https://user-images.githubusercontent.com/39735549/55708158-7feafc00-59e5-11e9-9969-caa4da30b2fc.png)

**Comment by HenriKorver** [comment]
@TCIMEddy Dank. Bovenstaande vragen waren een brain dump in 5 minuten ter inspiratie. Die vragen ga ik nog indikken, herformuleren en smart maken.

**Comment by JanWillemKooi** [comment]
@HenriKorver Ik ben in Tribes. We kunnen de vragen samen doorlopen als je dat makkelijk vindt?

**Comment by HenriKorver** [comment]
@TCIMEddy  Hieronder een nieuwe versie voor mentimeter:
* De tutorial voor de API Testvoorziening is zinvol (schaal van 1 op 10)
* Ik ga de testvoorziening op 18/7 gebruiken (Ja, Nee, Misschien, Weet niet)
* Ik ga de testvoorziening integreren met mijn eigen ontwikkelstraat via de API (Ja, Nee, Misschien, Weet niet)
* Wat vind je de belangrijkste functionaliteit van de testvoorziening?
  * Playground: zodat ik zelf geen dockers hoef te installeren om te kunnen spelen met de API
  * Compliancy: het kunnen aantonen dat mijn API-provider of -consumer voldoet (aan de ZGW-standaard)
* Wat vind je het belangrijkst?
  * Dat zowel API-providers als -consumers getest kunnen worden.
  * Dat voornamelijk API-providers getest kunnen worden
  * Dat voornamelijk API-consumers getest kunnen worden
* Wat mis je in de testvoorziening? 
* Welke user stories mis je nog?
* Zijn er nog non functionals die je gerealiseerd wilt zien?
* Wat voor ondersteuning heb je nodig van VNG om de testvoorziening te gebruiken?
* Hoe wil je als leverancier betrokken worden bij beheer en doorontwikkeling?
* Vragen?
