### ISSUE TITLE
As a tester I want to be able to match query parameters

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#108]
such that I can test consumer applications in more detail.

**Toelichting**:
It the scenarios cases it should be possible to specify patterns like this:
```/quotes?sort={field}```

**Oplossingsrichting**:

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/3 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by AlviseSembenico** [comment]
Since the order of the parameter is not fixed, I was wondering if it would be better to just specify the list of the parameter that are expected instead of hand encoding it directly in the url.

**Comment by HenriKorver** [comment]
You're completely right

**Comment by alextreme** [comment]
Implemented on vng-staging and verified. I noticed a bit of duplication in the query params column which Alvise will fix but besides this it's working as expected (tested with Demo API session type):

![Screenshot_2019-04-12_18-37-39](https://user-images.githubusercontent.com/226839/56052783-99c47000-5d52-11e9-9721-493ae18cd9a1.png)

**Comment by alextreme** [comment]
![Screenshot_2019-04-12_18-41-52](https://user-images.githubusercontent.com/226839/56052804-a8ab2280-5d52-11e9-8ffa-9e11abd23506.png)

**Comment by alextreme** [comment]
Now also is displayed as expected, ready for review

![Screenshot_2019-05-16_14-50-52](https://user-images.githubusercontent.com/226839/57855075-159a5800-77ea-11e9-9259-13563ec1960f.png)
