### ISSUE TITLE
As a tester I want a better report of the provider run

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#109]
such that I can exactly verify which assertions have been satisfied

**Toelichting**:
This is the current report of a provider run:
https://vng-staging.maykin.nl/server/98/pdf/111

This is the way how Postman shows the results:
![afbeelding](https://user-images.githubusercontent.com/37145898/55506024-bf67c000-5654-11e9-818b-634d416b7d07.png)

Furthermore, the kind of admin configuration as depicted below should then not be needed anymore:
![afbeelding](https://user-images.githubusercontent.com/37145898/55506705-69941780-5656-11e9-9680-f11c00345abb.png)

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by AlviseSembenico** [comment]
![aaa](https://user-images.githubusercontent.com/28757412/55885141-aa85b200-5ba9-11e9-866c-2ce17253c813.png)

**Comment by AlviseSembenico** [comment]
![aaa](https://user-images.githubusercontent.com/28757412/55887130-4369fc80-5bad-11e9-94c6-7a9c5ba9010f.png)

I improved the visualization trying to make it more similar to the postman as possible.

**Comment by alextreme** [comment]
The PDF report now contains the same data as shown on the server-run detail-page (including assertions).
