### ISSUE TITLE
Als VNG wil ik dat de testvoorziening open source beschikbaar is

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#11]
Deze user story is wellicht een acceptatiecriterium

**Comment by melsk-r** [comment]
Henri gaf in het PO overleg van 4 februari 2019 al aan dat hij de testvoorziening graag in beheer genomen ziet worden. Ik vraag me af wat de consequenties zijn voor beheer als de testvoorziening open source is.

**Comment by TCIMEddy** [comment]
@HenriKorver Zet jij de behoefte vanuit project Testvoorziening ook nog als user stories op deze Backlog. En kun je de vraag beantwoorden van @melsk-r. @melsk-r als je antwoord verwacht zet dan even de persoon die moet beantwoorden met een @TCIMEddy

**Comment by TCIMEddy** [comment]
@melsk-r Ik vraag me overigens af of dit een user story is of een acceptatiecriterium (dus algemeen principe)

**Comment by HenriKorver** [comment]
@TCIMEddy Heb de userstory ingediend bij api-beheer:
https://github.com/VNG-Realisatie/api-beheer/issues/88

**Comment by melsk-r** [comment]
> 
> 
> @melsk-r Ik vraag me overigens af of dit een user story is of een acceptatiecriterium (dus algemeen principe)

@TCIMEddy wat bedoel je in de bovenstaande zin precies met 'dit'?

**Comment by melsk-r** [comment]
@TCIMEddy Ik heb per ongeluk op de verkeerde knop geklikt. Zet jij het issue weer in de juiste kolom.

**Comment by alextreme** [comment]
Alles is open source gemaakt en gemerged in jullie master branch van deze repository.

Besproken met @HenriKorver en @JanWillemKooi , wij zien dit als een acceptatiecriterea en begrijpen dat dit nu is zoals het is afgesproken.
