### ISSUE TITLE
As  a tester I also want to use the PATCH-operation in scenario cases (besides POST, GET, PUT and DELETE)

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#113]
such that I can test the most common HTTP-scenario's

**Toelichting**:
...

**Oplossingsrichting**:
Add PATCH to the dropdown box below:
![afbeelding](https://user-images.githubusercontent.com/37145898/55668609-8a35ba80-586c-11e9-9725-fa27b706c32c.png)

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
This issue is related to #103

**Comment by AlviseSembenico** [comment]
Implemented in c8036a9ba8765e6971c5b72dea208854e39e4c0a

**Comment by alextreme** [comment]
Bij deze op vng-staging:

![Screenshot_2019-04-09_11-18-19](https://user-images.githubusercontent.com/226839/55788789-471c5700-5ab9-11e9-9505-723f500a3595.png)

**Comment by HenriKorver** [comment]
The PATCH entry has indeed been added to the drop down box but it does work properly yet, see #103
