### ISSUE TITLE
Rewrite problem in the docker version of the Demo API

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#122]
# Bug

See https://vng-staging.maykin.nl/737/.

In the docker version version the url returned after a POST-call misses a slash after maykin.nl (see below). Is this a uri-rewite problem?

```
POST /api/v2/quotes HTTP/1.1
Host: 155506251661-vng-staging.maykin.nl
Content-Type: application/json
cache-control: no-cache
Postman-Token: 840706cb-5ff3-4841-be08-fce505a6353b
{
    "tekst": "To be or to be",
    "bronNaam": "Shakespeare 3",
    "bronLink": "http://citation.org"
}
```
```
{
    "url": "https://155506251661-vng-staging.maykin.nlapi/v2/quotes/c1d0bd67-4ad7-46ea-94bd-7f8c950a073a",
    "tekst": "To be or to be",
    "bronNaam": "Shakespeare 3",
    "bronLink": "http://citation.org",
    "aangemaakt": "2019-04-12T09:53:03.764352Z",
    "laatstBijgewerkt": null
}
```

**Comment by alextreme** [comment]
Yes it is, this is the error we came across yesterday with:

https://github.com/VNG-Realisatie/api-testvoorziening/issues/103#issuecomment-482163434

"We have found an error with the Docker version of the Demo API that Alvise is working on, however the hosted version worked for me without problems."

**Comment by AlviseSembenico** [comment]
The solution dwells here de21cf61631a76168068adc4e048f97d03e96387

**Comment by AlviseSembenico** [comment]
![aaa](https://user-images.githubusercontent.com/28757412/56035967-e183d100-5d2b-11e9-8d2b-6230da7a08e2.png)

**Comment by HenriKorver** [comment]
Great, but I will only review it when it is rolled out on staging

**Comment by alextreme** [comment]
Feel free then:

![Screenshot_2019-04-12_15-16-52](https://user-images.githubusercontent.com/226839/56040146-0bda8c00-5d36-11e9-8d30-aa5bfbeabfb1.png)

**Comment by HenriKorver** [comment]
Yes, it works now!
