### ISSUE TITLE
Cannot move the scenario cases in the right order

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#129]
# Bug

![afbeelding](https://user-images.githubusercontent.com/37145898/56232339-ce049d00-6080-11e9-9b81-a4be84a41675.png)

**Comment by alextreme** [comment]
Alvise's fix for this issue has been reviewed and merged, he can try this out on vng-test

**Comment by AlviseSembenico** [comment]
Fixed in https://github.com/VNG-Realisatie/api-testvoorziening/pull/131/commits/2dbde1cb6a165e0780766a7e8d6a475b2c4cc429
