### ISSUE TITLE
Als provider-tester wil ik dat de interacties per call gevalideerd kunnen worden tegen json-schema

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#13]
zodat de te testen applicatie alleen valide berichten stuurt.

**Toelichting**:
Dit betreft alleen het testen van de response wanneer de te testen applicatie de provider is van de api.
In alle andere situaties wordt het bericht al gevalideerd door de referentie-implementatie en kan de testvoorziening het resultaat van deze validatie afleiden uit het antwoord van de referentie-implementatie.

**Oplossingsrichting**:
De testvoorziening valideert de response body tegen joon-schema.

In de scenariostap moet te configureren zijn dat deze validatie gewenst is.

Wanneer de validatie faalt, faalt de teststap en daarmee de testuitvoering.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by HenriKorver** [comment]
Provider API's are tested with Postman scripts that are uploaded to the test platform. Postman allows for JSON Schema validation, see [here](https://blog.getpostman.com/2017/07/28/api-testing-tips-from-a-postman-professional/).
