### ISSUE TITLE
As a user I want consistent and clear endpoints returned by the test platform

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#137]
such that I can quickly understand and use the platform for testing.

**Toelichting**:
When I start a consumer session of type "Demo API" I get for instance the URL 
[155551291847/demo-api](https://155551291847-vng-staging.maykin.nl/) back: 
![afbeelding](https://user-images.githubusercontent.com/37145898/56349477-ea135600-61c8-11e9-9a27-daf9e8f02e53.png)

This links to https://155551291847-vng-staging.maykin.nl/. However, it should be https://155551291847-vng-staging.maykin.nl/demo-api/api/v2.

Moreover, I would like to have a straightforward translation such that the hostname of the test platform is directly mapped to the endpoint of the API:

https://155551291847-vng-staging.maykin.nl should be mapped to https://ref.tst.vng.cloud. 

At the moment this is not the case. For instance:

https://155551291847-vng-staging.maykin.nl/demo-api 

does not link to same page as 

https://ref.tst.vng.cloud/demo-api

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by AlviseSembenico** [comment]
#136

**Comment by alextreme** [comment]
This seems like two similar but different requests in one user story, of which the second one I think can be solved with a different endpoint configuration.

I'd like to discuss this properly preferably with both of you before determining how to resolve this, because I don't think Alvise's change solves the whole story.

**Comment by alextreme** [comment]
Discussed with Henri and Alvise:
- Test session: split up the VNG endpoint URL field into a URL (normally containing only the domain name) and  a separate path field
- The path is used only for the link shown to the end-user in the test-session overview
- Remove the numeric part of the link shown, only show the path of the VNG endpoint 

eg: 
URL: https://ref.tst.vng.cloud/demo-api/api/v2 -> 
  URL: https://ref.tst.vng.cloud 
  Path: /demo-api/api/v2

In the Test session UI only show '/demo-api/api/v2' as the link to the test session's endpoint

**Comment by alextreme** [comment]
This has been deployed to vng-staging, and I've split all the session types to have a path separate from the domain.

Feel free to review
