### ISSUE TITLE
Als tester/testcoördinator (leverancier) wil ik een testrapport (bewijs van succesvol uitvoeren van de test) van een uitgevoerde test kunnen downloaden

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#15]

**Comment by fsamwel** [comment]
In de software catalogus kan een leverancier aangeven compliant te zijn aan een berichtenstandaard. Dit moet aan potentieel klanten (gemeente) bewezen kunnen worden.

Soms wordt een napi-standaard gedeeltelijk ondersteund. Bijvoorbeeld een client gebruikt maar een deel van de beschikbare operaties van een api.

Er moet dan op een voor de klant (gemeente-ambtenaar) vriendelijke en duidelijke manier gepresenteerd worden:
- dat de applicatie compliant is
- welke versie van de applicatie compliant is
- welk deel van de api-standaard ondersteund wordt door de applicatie

Nu is dat geregeld via het downloaden van een pdf. Voor mij is dat geen eis. Een andere vorm van presentatie is ook prima. Zolang dit maar via de softwarecatalogus te tonen is én de presentatievorm vriendelijke en duidelijk is.
Bijvoorbeeld dat de softwarecatalogus een api (van de testvoorziening) aanroept en presenteert aan de bezoeker, waarin gevraagde informatie wordt getoond.

N.B. de hier bedoelde functionaliteit is iets anders dan het opvragen van het testresultaat door de tester of door de CI-tooling t.b.v. regressietest.

**Comment by melsk-r** [comment]
Verwachten je dat beheer de testrapporten nog moet gaan accorderen voordat deze door de leverancier gebruikt kunnen worden als bewijs naar hun klanten? Volgens mij is dat in de huidige situatie (STP) nl. wel het geval.
Zo ja dan ben ik benieuwd hoe dat proces van accorderen er uit gaat zien.
Zodra dat duidelijk is kan ik beslissen of ik daar dan een aparte userstory voor in moet schieten.

**Comment by TCIMEddy** [comment]
@HenriKorver Wellicht nog wat vroeg in het proces maar kun je al antwoord geven (of richting) op de vraag van Robert (lijkt bijna wel samenwerken en afstemmen :-)

**Comment by HenriKorver** [comment]
In mijn perceptie worden testrapporten volledig automatisch aangeboden, ook als het gaat als fysiek bewijs. Het mooist is als de testrapporten door de testvoorziening worden bewaard en toegankelijk zijn via een permanente link. Dat maakt rapportvervalsing een stuk lastiger.
@melsk-r @michielverhoef Kunnen jullie achterhalen waarom bij de STP er nog een handmatig accorderingsproces nodig is?

**Comment by michielverhoef** [comment]
Dat is vrij simpel: helaas zijn het STP en de Softwarecatalogus bij mijn weten nog niet aan elkaar gekoppeld.

Op dit moment moeten leveranciers zelf aangeven of een pakket compliant is en het bijbehorende testrapport aanleveren. Omdat hier in het verleden fouten mee gemaakt zijn is besloten de rapporten voordat ze daadwerkelijk getoond worden eerst handmatig te controleren om zeker te zijn dat onder andere:
* Het rapport ook gaat over de juiste standaard en versie daarvan
* Het rapport geen fouten bevat en alle (verplichte) tests succesvol doorlopen zijn
* De versie van de applicatie overeenkomt met de versie die getest is
* De applicatie de standaard ook in de juiste rol ondersteunt en daarop getest is

Gezien de opzet van beide systemen zou ik er voor willen pleiten om ook de softwarecatalogus eens zeer kritisch onder de loep te nemen en te beoordelen of de huidige opzet wel past binnen de ontwikkelingen van de Common Ground en integratie met de testvoorziening etc.  (dat is dus niet zo kan ik je al verklappen ...).

**Comment by HenriKorver** [comment]
@michielverhoef Dank voor deze interessante observaties. De ATV zal niet geïntegreerd worden met de Softwarecatalogus, maar met een API-catalogus zoals mogelijk developer.overheid.nl. Het is dan zaak dat we niet dezelfde fouten maken.
