### ISSUE TITLE
Als VNG wil ik dat er meerdere api's tegelijkertijd getest kunnen worden

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#16]

**Comment by HenriKorver** [comment]
Nu kunnen we in de ATV alleen de API's testen van ZGW. De wens is om ook andere API's te kunnen testen.
@joeribekker Jij hebt toch een soort van demo API gemaakt. Kunnen we die voor deze US gebruiken?

**Comment by HenriKorver** [comment]
Het is inmiddels aangetoond dat we zowel de demo-api als de zwg-api tegelijk kunnen testen
