### ISSUE TITLE
In badge-mode I should be able to acces the PDF-report and HTML/JSON logging files directly without first logging in

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#167]
# Bug
If I click on a badge 
[![Status badge](https://img.shields.io/endpoint.svg?style=for-the-badge&amp;url=https://vng-staging.maykin.nl/api/v1/provider-run-shield/135/)](https://vng-staging.maykin.nl/server/d28ca332-f2ee-4b95-9918-d94a24da96c3)

and go the detail page of the test:
https://vng-staging.maykin.nl/server/d28ca332-f2ee-4b95-9918-d94a24da96c3

then I cannot acces the logging files  and the PDF report without logging in first

**Comment by HenriKorver** [comment]
@alextreme Can you solve this bug in the current sprint?

**Comment by AlviseSembenico** [comment]
Fixed in this commit https://github.com/VNG-Realisatie/api-testvoorziening/pull/162/commits/c601c07ac3deda4695f9a5af2374d3cb7a9c59b8
that will be verified within this PR  https://github.com/VNG-Realisatie/api-testvoorziening/pull/162

**Comment by alextreme** [comment]
PDF is exposed to end-users, however the HTML and JSON output also needs to be accessible by anonymous users. This is not yet the case.
