### ISSUE TITLE
Problem with slashes in provider report

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#168]
# Bug
See this report: https://vng-staging.maykin.nl/server/d28ca332-f2ee-4b95-9918-d94a24da96c3

There are double slashes in urls such as:

![afbeelding](https://user-images.githubusercontent.com/37145898/57531914-dfb52980-733a-11e9-8d8f-316d5f885de8.png)

This is probably caused by the wrong trailing slash here:

![afbeelding](https://user-images.githubusercontent.com/37145898/57531982-04110600-733b-11e9-9a7c-fd12fe5f8d07.png)

Although the URLs are wrong the tests still succeed. Strange!

**Comment by AlviseSembenico** [comment]
It is the correct behaviour since the postman collection has been configured to add the slash. To avoid it just use https://vng-staging.maykin.nl/server/141 as url as in this https://vng-staging.maykin.nl/server/141

**Comment by AlviseSembenico** [comment]
The fact that the tests succeed is because both urls https://ref.tst.vng.cloud/demo-api/api/v2/quotes
https://ref.tst.vng.cloud/demo-api/api/v2//quotes retrieve the same resource.

**Comment by HenriKorver** [comment]
Thanks for your explantions, now I understand what happened. When starting the run I entered ttps://ref.tst.vng.cloud/demo-api/api/v2/quotes/ as the endpoint of the provider to test which was wrong because of the trailing slash. It would be nice if the testplatform could validate on this. I will make a new user story for this
