### ISSUE TITLE
Als VNG wil ik dat er meerdere versies van een api tegelijkertijd kunnen zijn en getest kunnen worden

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#17]
zodat alle ondersteunde versies van een api (standaard) getest kunnen worden.

**Toelichting**:
Wanneer er een nieuwe (major) versie van een api (standaard) komt, wordt de vorige versie nog langere tijd ondersteund (bijv. nog 6 maanden of één jaar). In die tijd moet ook deze vorige versie van de api getest kunnen worden. Zo kunnen er dus ook 3 of 4 of ... versies van dezelfde api getest moeten kunnen worden (oké het is erg onwenselijk dat er zoveel breaking changes zijn, maar ...  als je 2 versies kan ondersteunen waarom dan niet gewoon > 1)

**Oplossingsrichting**:
We beschouwen een nieuwe versie van een api als andere api die onafhankelijk te configureren is.

Een te testen api (standaard) wordt geïdentificeerd op de combinatie api-naam plus api-versie.

- Het is wenselijk dat scenario's van de vorige versie hergebruikt kunnen worden voor de nieuwe versie.
- En het is (zeer!) wenselijk dat scenario's van de vorige versie gekopieerd kunnen worden zodat voor de nieuwe versie aanpassingen kunnen worden gedaan en de beheerde niet helemaal opnieuw moet beginnen met het opvoeren van de configuratie.
Voor beide bovenstaande punten geldt dat het belang hiervan afhangt van de manier waarop scenario-configuratie wordt gedaan. Wanneer bijvoorbeeld de scenario-configuratie wordt ingelezen uit een configuratiebestand (of Excel ofzo) krijg je deze mogelijkheden vanzelf.\
- In de API strategie staat er op dit moment dat er maximaal 3 versies van een API ondersteund hoeven te worden.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by melsk-r** [comment]
In de API strategie staat er op dit moment dat er maximaal 3 versies van een API ondersteund hoeven te worden.

**Comment by TCIMEddy** [comment]
@melsk-r Lijkt me dan ook prima uitgangspunt. @HenriKorver mee eens neem ik aan?

**Comment by HenriKorver** [comment]
Ja, prima, maar als de testvoorziening toch meerdere versies van een API moet kunnen ondersteunen dan maakt het niet zoveel uit of je dat voor 3 of voor N versies bouwt

**Comment by HenriKorver** [comment]
Het is mogelijke om met de testvoorziening meerder versies van een api tegelijk te testen
