### ISSUE TITLE
Als VNG wil ik dat meerdere leveranciers tegelijkertijd en onafhankelijk van elkaar tests kunnen uitvoeren

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#18]
zodat de tests elkaar niet negatief kunnen beïnvloeden.

**Toelichting**:
In het huidige prototype wordt bij het testen van verschillende clients dezelfde referentie-implementatie gebruikt als provider. Deze tests kunnen met elkaar interfereren omdat alle calls op dezelfde database worden uitgevoerd. Dat is niet wenselijk

**Oplossingsrichting**:
Bij elke client-test de provider als nieuwe (docker-)container opstarten. Als de test is afgerond de container weer vernietigen.

**Definition of ready**
- [X] Iedereen in het team begrijpt de user story
- [X] Is klein genoeg (maximaal 1/3 van sprint)
- [X] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [X] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [X] Voorzien van Definition of Done (duidelijk en testbaar)
- [X] Voorzien van taken
- [X] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [X] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [x] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [x] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] Gereviewd
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by alextreme** [comment]
De behoefte hier is dat de Demo API uit #67 (naast als vaste API voor het ATV) ook dynamisch per client test-sessie opgestart kan worden en los van de andere leveranciers van het ATV beschikbaar wordt gesteld.

**Comment by alextreme** [comment]
Demo API is als Docker image geschikt gemaakt voor het test-platform.
Huidige koppeling van vng-test/vng-staging is met de Test-platform Kubernetes cluster op GCP.

**Comment by JanWillemKooi** [comment]
Tijdens de demo kwam nog een issue naar boven wat opgelost moet worden.
- Docker kan niet opgestart worden vanuit een Postman sessie
- Rewrite van de URL's werkt nog niet (2x HTTPS)

**Comment by alextreme** [comment]
Het rewrite-probleem is verhopen op vng-staging.

Het opstarten van Docker via de API was al mogelijk, echter hiervoor is een andere manier van opstarten nodig (er moet gewacht/gepolled worden totdat de status van de sessie 'running' is) aangezien het langer duurt dan wat mogelijk is binnen 1 call. Dit vereist dan wel een additionele stap in de Postman collections van Henri.

**Comment by HenriKorver** [comment]
Klaar
