### ISSUE TITLE
Test consumer: postman collections with Docker session-types

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#183]
# Bug

From #44 

As described by @HenriKorver replacement of the 'demo-api' variable in the Postman collection only works if it is filled in, and this is only the case when the consumer test session is running against a hosted API.

For the Docker containers the Url field remains empty, so this needs to be filled in differently by the Docker IP address instead to ensure the Postman collection can be run against the GCP pod:

![57970019-532eea80-797c-11e9-847b-e01494d94ad4](https://user-images.githubusercontent.com/226839/58008008-bd19d200-7aeb-11e9-9873-2368f4118d1d.png)

**Comment by AlviseSembenico** [comment]
This situation is handled here, https://github.com/VNG-Realisatie/api-testvoorziening/commit/49e37ac07f28f01060c74005916deb336f5f4512

https://github.com/VNG-Realisatie/api-testvoorziening/blob/624f5eec8b043fb70d3ba2f4806572371f2827ef/src/vng/testsession/task.py#L156

**Comment by HenriKorver** [comment]
When I try to test this it still seems to go wrong. See session (908): https://vng-staging.maykin.nl/0ef69027-8992-4990-8f19-8bd8a2d9c285/

![afbeelding](https://user-images.githubusercontent.com/37145898/60026608-2321e800-969c-11e9-8494-53343ce7ce84.png)

**Comment by alextreme** [comment]
This is likely due to the same issue as #86, we'll investigate further thanks

**Comment by AlviseSembenico** [comment]
@HenriKorver I added the path also for the docker image, now it works as expected https://vng-staging.maykin.nl/efae4325-d68e-4f3c-9a7e-e9748bda0123/
![image](https://user-images.githubusercontent.com/28757412/60178360-a158c880-981b-11e9-8826-0fcf7e8e5364.png)

**Comment by HenriKorver** [comment]
Alvise, which user must I hijack to see the results of this link https://vng-staging.maykin.nl/efae4325-d68e-4f3c-9a7e-e9748bda0123/?

**Comment by AlviseSembenico** [comment]
I updated staging, you should be able to access the resource without hijack anyone.

**Comment by HenriKorver** [comment]
Thanks
