### ISSUE TITLE
Cannot acces information about testsession via API

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#184]
# Bug

Although the testsession is running I get te message that the resource has been turned off.

![afbeelding](https://user-images.githubusercontent.com/37145898/58048853-d3f01100-7b4b-11e9-9aad-d75ca4143257.png)

**Comment by alextreme** [comment]
You want the URL with a slash, this works as expected:

https://vng-staging.maykin.nl/api/v1/testsessions/873/

![Screenshot_2019-05-21_14-35-11](https://user-images.githubusercontent.com/226839/58096563-a780d700-7bd5-11e9-8de1-dd4857766045.png)

See also (which should raise a 404 but offers the same response as which Henri encountered):

https://vng-staging.maykin.nl/afsdfsdfsdf

It seems the 404 which is generated here is being unintentionally caught by the proxy, which can't resolve the URL. 

@AlviseSembenico feel free to investigate. Also ensure slashes at the end of the API detail-endpoints are optional, and add a regressiontest to deal with both the missing slash and to ensure a non-proxied 404 simply gives a 404 (if possible, I understand this may be complicated)

**Comment by AlviseSembenico** [comment]
#188
