### ISSUE TITLE
Badge is green but test failed

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#186]
# Bug

https://vng-staging.maykin.nl/server/a1660a86-3312-48f6-8106-4fa9dec1e8f7

In the screen shot below one sees a green badge but also red crosses:

![afbeelding](https://user-images.githubusercontent.com/37145898/58120839-576e3880-7c06-11e9-9d54-8a00ebe9f1be.png)

**Comment by alextreme** [comment]
Maybe the previous badge success-state was cached? I'll have Alvise investigate

**Comment by AlviseSembenico** [comment]
Now it behaves as expected.

![image](https://user-images.githubusercontent.com/28757412/58697105-40afaa80-8399-11e9-8134-3e67beb7db9e.png)

**Comment by HenriKorver** [comment]
@AlviseSembenico There is still a problem, see screenshot below (green badge, but 6 calls failed and 7 assertions failed)
![afbeelding](https://user-images.githubusercontent.com/37145898/58875123-fc8b1580-86ca-11e9-86fd-6ae9c041e28d.png)

**Comment by AlviseSembenico** [comment]
@HenriKorver 
The problem is that the summary is not displayed correctly, in fact, as you can see all the calls are successful 
![image](https://user-images.githubusercontent.com/28757412/58945990-36205700-8785-11e9-9806-8e7d1cd5bb23.png)

Nonetheless, this problem has already been adressed.

**Comment by HenriKorver** [comment]
Allright, so this problem is already being addressed in #192. So I can close this one
