### ISSUE TITLE
Test consumer: Ensure endpoint variable for post-run Postman collection contains both URL and path

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#189]
# Taak

From #44 from @HenriKorver 

Currently the {{ demo-api }} variable is translated to only the URL of the VNG-endpoint. More consistent (with the scenario cases) would be to translate this variable to the URL + Path of the VNG-endpoint.

**Comment by AlviseSembenico** [comment]
The line 153 replace with url + path
https://github.com/VNG-Realisatie/api-testvoorziening/blob/624f5eec8b043fb70d3ba2f4806572371f2827ef/src/vng/testsession/task.py#L153

**Comment by HenriKorver** [comment]
I cannot test this because of bug #215.

**Comment by HenriKorver** [comment]
Because of the work-around of @alextreme pointed out in #215 I could finally test it and it worked.
