### ISSUE TITLE
Summary information seems incorrect

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#192]
# Bug

Although the server-run was successful, the summary states that there are errors:

![Screenshot_2019-05-27_12-39-15](https://user-images.githubusercontent.com/226839/58414830-ddfa9e00-807c-11e9-9014-43eb6912093d.png)

**Comment by alextreme** [comment]
@HenriKorver ter info

**Comment by AlviseSembenico** [comment]
Now the behavior is as expected.

![image](https://user-images.githubusercontent.com/28757412/59927427-be1c8700-943c-11e9-85e6-f1b2a942cb15.png)

**Comment by HenriKorver** [comment]
In the summary report the colors are wrong: errors should be red but are green.
![afbeelding](https://user-images.githubusercontent.com/37145898/60014873-4cce1580-9682-11e9-9292-6e1dedd9e551.png)

**Comment by alextreme** [comment]
Well-found, I've switched the styling (may need to refresh your page):

https://vng-staging.maykin.nl/665a318f-ec8d-4fb9-a9de-c5287b040e86/
![Screenshot_2019-06-24_15-44-18](https://user-images.githubusercontent.com/226839/60023856-f3241600-9696-11e9-8e8b-47354707f816.png)
