### ISSUE TITLE
Improved Newman HTML report

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#193]
# Bug

This seems to be removed from vng-staging, could you reactivate the 'pretty' Newman HTML reports for provider tests?

**Comment by AlviseSembenico** [comment]
New html reporter working properly.
![image](https://user-images.githubusercontent.com/28757412/59928051-291a8d80-943e-11e9-99e9-66d76302f70a.png)

**Comment by HenriKorver** [comment]
On the test server when I click on the link "Visualize HTML log" it hangs:

![afbeelding](https://user-images.githubusercontent.com/37145898/60015542-0bd70080-9684-11e9-9bd1-51ddc1a3ba4e.png)

**Comment by alextreme** [comment]
I've verified this with the following new session on vng-staging and it seems to work as expected:

https://vng-staging.maykin.nl/server/92c8cf3d-c6c0-4d8a-b3ec-2c8dad2fb0a9
https://vng-staging.maykin.nl/server/92c8cf3d-c6c0-4d8a-b3ec-2c8dad2fb0a9/log

![Screenshot_2019-06-24_15-39-56](https://user-images.githubusercontent.com/226839/60023564-5497b500-9696-11e9-839a-7bcf91c9378b.png)

**Comment by HenriKorver** [comment]
It is also working here now. Maybe it was a temporary problem at the server
