### ISSUE TITLE
Als gebruiker wil ik mijn wachtwoord kunnen wijzigen

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-testvoorziening#195]
...zodat ik bijv. een toegekend wachtwoord kan aanpassen maar ook, indien ik dat wens, mijn wachtwoord regelmatig kan veranderen.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
It is already possible to change your password by using the button `Wachtwoord vergeten?`. However maybe you also want do be able to change your password via your profile. For this feature one is referred to user story #196.
