### ISSUE TITLE
URL veld heeft geen label

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-testvoorziening#201]
# Bug

Bij het opstarten van een provider sessie kom je op een gegeven moment in een scherm waarin je de url van de te testen api moet invullen. Dat veld heeft geen label en is ook niet gevuld met een duidelijke voorbeeldwaarde. Voorzie daarin.

[assign aan teamlid en voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZDS Realisatie Huidige Sprint']

**Comment by alextreme** [comment]
Discussed with Henri. The request here is to ensure that the placeholders shown (now 'ZRC', 'DRC') is an actual url: http://www.example.com. This should make it clear that the required input for the field is indeed a URL.

**Comment by AlviseSembenico** [comment]
1aadd216bc02b85f0eba8096e87945c174f89973

**Comment by HenriKorver** [comment]
At staging I do not get the desired result:

![afbeelding](https://user-images.githubusercontent.com/37145898/60013879-e7792500-967f-11e9-8b3d-4680b62b6c6c.png)

**Comment by alextreme** [comment]
I've updated vng-staging:

https://vng-staging.maykin.nl/server/2/create

![Screenshot_2019-06-24_14-13-06](https://user-images.githubusercontent.com/226839/60017942-3d52ca80-968a-11e9-8f48-1aa33c03059a.png)

**Comment by alextreme** [comment]
And note that the above link is only for demonstration purposes (it is a deeplink to step 2 of this form).

For actually correctly starting a testrun you need to start at: https://vng-staging.maykin.nl/server/create

**Comment by HenriKorver** [comment]
thanks, it works now!
