### ISSUE TITLE
Het testen van de Demo API geeft een foutief resultaat

### ISSUE THREAD

**Issue by melsk-r** [VNG-Realisatie/api-testvoorziening#203]
# Bug

In het scherm ‘Postman collection – eerste resultaat tabel’ staat dat de test niet succesvol is verlopen terwijl je, als je verder naar beneden scrolled, ziet dat de test wel goed verlopen is.

[assign aan teamlid en voeg label 'bug' toe, kies bij 'projects' voor 'Scrum ZDS Realisatie Huidige Sprint']

**Comment by HenriKorver** [comment]
Dit probleem wordt al getackeld in #192.
