### ISSUE TITLE
As PO I want testreports to contain relevant information about the tested supplier/software product 

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#205]
such that it is clear which consumer or API-provider has been tested

**Toelichting**:
...

**Oplossingsrichting**:
A supplier must be able to provide additional information per testsession, such as:

* Name of the supplier (with a link to the website)
* Name of the software product ((with a link to the website)
* Role of the product (for example: zaaksysteem, MOR-applicatie, zaak-consumer, zaakbeheer-systeem, zaaktypemagazijn)

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
The request is to be able to fill in these 3 fields after the session has been created, they are optional. The badge is still given and shown if this is not filled in.

At a later stage the badge will only be given if the 3 fields are filled in.

**Comment by AlviseSembenico** [comment]
https://github.com/VNG-Realisatie/api-testvoorziening-code/pull/4

**Comment by AlviseSembenico** [comment]
present in both sides and updatable
![image](https://user-images.githubusercontent.com/28757412/59929457-23727700-9441-11e9-87e9-a90901dda935.png)
![image](https://user-images.githubusercontent.com/28757412/59929545-50bf2500-9441-11e9-8637-ec36ac327525.png)

**Comment by HenriKorver** [comment]
In the screen of the provider test the supplier information should have its own place.
![afbeelding](https://user-images.githubusercontent.com/37145898/60014510-79356200-9681-11e9-8d7b-2fa3871c54c1.png)

**Comment by alextreme** [comment]
@HenriKorver could you clarify how you'd want this to be displayed? Otherwise we can leave this until thursday if you want to discuss this in person.

**Comment by HenriKorver** [comment]
In the screen of the consumer test it is done the right way (supplier information is dispayed in a seperate table):

![afbeelding](https://user-images.githubusercontent.com/37145898/60016928-dcc28e00-9687-11e9-8861-3751f000f039.png)

**Comment by alextreme** [comment]
Clear, thanks!

**Comment by HenriKorver** [comment]
By the way, could you rename the header of this table as follows:

Information -> Supplier information

**Comment by AlviseSembenico** [comment]
@HenriKorver is it as you thought right?
![image](https://user-images.githubusercontent.com/28757412/60179401-e54ccd00-981d-11e9-9e15-ac693a69e807.png)

**Comment by HenriKorver** [comment]
Almost right.  There is only a typo left: "Information -> Supplier informtion" should be  "Supplier informtion".

**Comment by AlviseSembenico** [comment]
Sorry Henry, I don't see it, where?

**Comment by HenriKorver** [comment]
![afbeelding](https://user-images.githubusercontent.com/37145898/60255529-3c12df00-98d0-11e9-99a4-cc31efb7ef0a.png)

**Comment by AlviseSembenico** [comment]
Ah you mean without "information ->"? i though i mistyped information.
Done

**Comment by HenriKorver** [comment]
You say done but I do not see the correction at the test or staging server

**Comment by AlviseSembenico** [comment]
I pushed the code, I am deploying now

**Comment by AlviseSembenico** [comment]
![image](https://user-images.githubusercontent.com/28757412/60258194-f0166900-98d4-11e9-9dab-63fc4fcf4ae8.png)
