### ISSUE TITLE
Uitwerken Sprint 0 - aftrap

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#31]
[Scrum API-testvoorziening v1.1.pptx](https://github.com/VNG-Realisatie/api-testvoorziening/files/2592739/Scrum.API-testvoorziening.v1.1.pptx)
j

**Comment by joeribekker** [comment]
👍 

De slide "overige" lijkt me een beetje losstaand? Verder prima.
Wel vroeg ik me af wat de betekenis is van een low-prio User Story. In Scrum kan deze aan het einde van X sprints bijvoorbeeld nog niet zijn opgepakt. Maar in dit geval moeten alle (niet geweigerde) User Stories ten minste in de specificatie komen. Anders is de specificatie niet compleet.

Uiteraard kunnen we die User Stories wel 1-op-1 opnemen in een aanbesteding zodat de opdrachtnemer daar een zelf alsnog invulling voor moet maken.

**Comment by fsamwel** [comment]
in slide 14 vind ik ambitie "31-03-2018 klaar" vrij ambitieus. 31-03-2019 is beter ;)
"4 sprints van 4 weken" ik dacht dat we sprints van 3 weken hebben afgesproken

**Comment by TCIMEddy** [comment]
Dank
- overige sheet gaat eruit
- datum uiteraard 2019
- en opmerking springlengte verwerk ik
