### ISSUE TITLE
Visie formuleren en toevoegen aan readme.md

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#32]

**Comment by HenriKorver** [comment]
@TCIMEddy Zojuist een eerste opzetje toegevoegd. Is dat voor nu even genoeg?

**Comment by TCIMEddy** [comment]
@HenriKorver Ziet er goed uit en close het voor nu. Aanpassingen uiteraard altijd mogelijk.
