### ISSUE TITLE
Als gebruiker van de testvoorziening wil ik een SLA op de test-voorziening

### ISSUE THREAD

**Issue by michielverhoef** [VNG-Realisatie/api-testvoorziening#34]
zodat ik weet onder welke voorwaarden ik gebruik kan maken van de test-voorziening.

**Toelichting**:
Denk aan:
* uptime/downtime
* onderhoud test-voorziening
* up-to-date zijn van testen (testen sluiten aan bij de nieuwste versie van een standaard etc.)
* binnen zoveel tijd kan ik (voor het eerst) gebruik maken van de test-voorziening
* Bij vragen/problemen kan ik terecht bij ...

**Oplossingsrichting**:
...

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by TCIMEddy** [comment]
@HenriKorver Graag prio en eventueel visie toevoegen

**Comment by HenriKorver** [comment]
Deze US is niet relevant voor de prototype, maar is uiteindelijk wel belangrijk voor de tekst van de aanbesteding.
@fsamwel Kun jij alvast een oplossingsrichting formuleren gezien jouw ervaringen met het SLA van de huidige testvoorziening (STP)?

**Comment by HenriKorver** [comment]
Omdat we geen aanbesteding gaan doen is deze user story out of scope
