### ISSUE TITLE
Als gemeente wil ik zeker weten dat de client-applicatie volledig compatible is met de api-provider(s)

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#36]
zodat ik zeker weet dat de client-applicatie zijn taken goed kan uitvoeren.

**Toelichting**:
Een client-applicatie zoals de MOR is afhankelijk van diverse provider-applicaties zoals zrc en ztc. Voor gemeente(n) is het belangrijk dat dergelijke koppelingen door een TV (Test Voorziening) zijn getest. 

**Oplossingsrichting**:
We gaan ervan uit dat de testscenario's worden aangeleverd vanuit de beheerder van de API-standaard. 
De TV zorgt ervoor dat deze scenario's uitgetest kunnen worden op de client. De client moet dan één of meerdere scenario's  uitvoeren na dat er een start-signaal is uitgestuurd.
Mogelijke voorbeelden van testopdrachten in de context van ZDS:
1. Maak een zaak aan met identificatie "12345" van het zaaktype "MOR" en geef een willekeurige geometrie mee.
1. Wijs de behandelaar  `Jan de Vries` toe aan de zaak `zaken\12345` en .zet de status op `in behandeling`.
1. Voeg aan deze zaak een document toe met als titel "Wateroverlast".
1. Voeg een besluit toe met besluitidentificatie "34455677".
1. Haal het bovengenoemde besluit op.
1. Sluit de zaak af.

De scenario's kunnen uit meerdere stappen bestaan. B.v. in scenario 2 zal eerste de uri van de behandelaar opgehaald moeten worden met een GET-request alvorens de behandelaar met een POST-operatie aan de zaak gekoppeld kan worden.

De TV kan twee soorten van validatie uitvoeren:
1. Validatie op de uitvoering. Per stap wordt het volgende getest:
   * De stap voldoet aan de voorgedefinieerde sequentie (indien dat wordt geëist).
   * Requests voldoen aan de gestelde eisen qua endpoint, headers, parameters en berichtinhoud.
   * Responses voldoen aan de gestelde eisen qua headers en berichtinhoud.
   * Geen foutmeldingen (4.xx / 5.xx etc.)

2. Validatie op het eindresultaat. Door middel van bijvoorbeeld GET-requests kan de TV checken of de gewenste eindtoestand bij de provider is bereikt nadat de client de testopdracht(en) heeft doorlopen.

Uiteindelijk moet de TV een rapportage van de uitgevoerde tests opgevraagd kunnen worden door middel van een api.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] De client moet ook gedeeltelijk getest kunnen worden
- [ ] ...
- [ ] ...

**Taken**
- [ ] Vaststellen welke userscenario's we gaan gebruiken in de prototype
- [ ] Ontwikkelen prototype
- [ ] Uittesten en reviewen prototype
- [ ] Opstellen specificatie voor de aanbesteding

**Comment by HenriKorver** [comment]
@fsamwel @alextreme Graag deze US aanvullen en verscherpen zodat we m kunnen meenemen in de eerste sprint

**Comment by melsk-r** [comment]
Je schrijft:
> **Oplossingsrichting:**
> We gaan ervan uit dat de testscenario's worden aangeleverd vanuit de beheerder van de API-standaard.

Ook hier geldt dat dit al wordt aangeleverd door de ontwikkelaar van de Open API standaard. 
Bij een aanpassing van de standaard (wat dus de verantwoordelijkheid van de beheerder is) geldt echter wel dat de beheerder er voor moet zorgen dat de aanpassingen ook doorwerken in de TV. Dus moet hij aangepaste of nieuwe testscenario's aanleveren.

**Comment by fsamwel** [comment]
> De client moet dan één of meerdere scenario's uitvoeren na dat er een start-signaal is uitgestuurd.

Het "startsignaal" triggert dat de testvoorziening:
* Een testuitvoering initialiseert (logging, enz.)
* Referentie-implementatie wordt gestart
* Terugmeldt welke endpoints beschikbaar zijn voor de test

**Comment by fsamwel** [comment]
> > Oplossingsrichting:

> We gaan ervan uit dat de testscenario's worden aangeleverd vanuit de beheerder van de API-standaard.
> Ook hier geldt dat dit al wordt aangeleverd door de ontwikkelaar van de Open API standaard.

Ik ben het eens met Robert. Technische werking en beschikbaarheid van de testvoorziening en content in de testvoorziening kan je in het beheer beter scheiden (separation of concerns).

Bovendien helpt het bij het ontwerp en beheer van een API wanneer de testbaarheid direct wordt getoetst door de test al te maken. En kan er direct ook de client-referentie-implementatie mee worden getest.

**Comment by fsamwel** [comment]
Voor het testen van een client moeten twee soorten scenario's ondersteund worden:
1. De client mag zelf kiezen welke operaties in welke volgorde worden aangeroepen. Alleen het resultaat in de provider-referentie-implementatie wordt gecontroleerd.
2. De client moet een aantal operaties in vastgestelde volgorde aanroepen. Er kunnen eisen aan de inhoud van de aanroepen worden gesteld (operatie, headers, parameters, request body).

Beide vormen kunnen evt. binnen één scenario worden gecombineerd.

Ad 1. de testvoorziening moet:
- weten dat (dit deel van) de test gestart is
- alle requests en responses die binnenkomen loggen
- alle requests en responses die binnenkomen valideren (meestal alleen op statuscode < 400)
- weten wanneer de client klaar is met het uitvoeren van de test (via een api aanroep)
- hierna requests kunnen doen naar de referentie-implementatie om het resultaat van de test op te halen

Ad 2. de testvoorziening moet geconfigureerde stappen kennen die:
- een fout loggen wanneer een ander bericht dan het verwachtte bericht wordt ontvangen
- het ontvangen bericht (van geconfigureerde operatie) valideren op operatie, headers, parameters en request body
- het antwoord van de referentie-implementatie (van geconfigureerde operatie) valideren op headers en response body

Een scenario kan dus bestaan uit (geconfigureerd worden met) de volgende soorten stappen:
- Teststap zoals beschreven bij 1.
- Teststap zoals beschreven bij 2.
- Teststap waarbij de testvoorziening een api request doet (richting referentie-implementatie) en het antwoord valideert

Bij elke teststap moet het mogelijk zijn een of meerdere validaties uit te voeren, zowel op het request als op het response. De validaties kunnen betrekking hebben op de request uri, path- en query-parameters, headers en body (met json-path locatie van elementen hierbinnen).

Schemavalidatie is niet nodig, want dat moet de referentie-component doen.

De testvoorziening moet zelf de volgende api operaties leveren:
- initialiseren van de test
- de uitvoering van een teststap zoals beschreven bij 1. is afgerond
- testresultaat/rapport
- De gebruiker moet de testvoorziening kunnen bevragen welke endpoints beschikbaar zijn voor de testuitvoering.

Ik kan me zo voorstellen dat het voor een client (leverancier) erg prettig is wanneer de endpoints bij elke testuitvoering op een bepaald scenario altijd gelijk is. Dat maakt het automatiseren aan hun kant veel makkelijker. 

Onderwerpen waar we nog over moeten nadenken:
- compliancy en versie van de client
- opnieuw uitvoeren van test (op nieuwe versie van client) en eerder behaalde compliancy
