### ISSUE TITLE
Als leverancier wil ik een api gedeeltelijk kunnen testen

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#4]

**Comment by fsamwel** [comment]
Met name clients van een api gebruiken niet altijd alle operaties van een api. Bijvoorbeeld wanneer een client alleen zaken wil kunnen zoeken en raadplegen, maar geen zaken wil toevoegen en wijzigen.

Deze client-applicatie kan toch compliant zijn aan de api-standaard, wanneer bij het opstellen van de api-standaard ook is afgesproken dat de client niet alle operaties hoeft te ondersteunen.
In dat geval moet het mogelijk zijn alleen een deel van de test uit te voeren, namelijk alleen voor die operaties die de client wél gebruikt.

Bij het configureren van de api-test moet de ontwikkelaar/beheerder ook ook kunnen aangeven of een test/scenario verplicht dan wel optioneel is voor compliancy.

Uiteraard is het voor "compliancy" aan een api-standaard wel verplicht dat er ten minste één operatie wordt ondersteund.

Ook moet in de compliancyrapportage, met name richting gemeente (vanuit software catalogus) zeer duidelijk zijn welke operaties wel en welke operaties niet worden ondersteund.

**Comment by HenriKorver** [comment]
#76 is gerelateerd aan dit issue

**Comment by HenriKorver** [comment]
In de testrapporten kan men zien welke stappen in de test zijn gelukt, mislukt of niet zijn uitgevoerd. Hiermee wordt het gedeeltelijk testen ondersteund.
