### ISSUE TITLE
Voorbeeldrapport opstellen voor MOR user story #36

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#40]
Op basis van #36 een voorbeeldrapport opstellen waarmee een gemeente kan zien dat de MOR client werkt zoals verwacht

**Comment by fsamwel** [comment]
twee varianten:
- json t.b.v. CI/regressietest (technisch leesbaar)
- html t.b.v. tonen vanuit softwarecatalogus

**Comment by fsamwel** [comment]
voor user story #36 is html variant voldoende, want "Als gemeente wil ik ..."

**Comment by fsamwel** [comment]
Zie hier het voorbeeld van de rapportage (html)

**Comment by alextreme** [comment]
Dank Frank, dit geeft wat mij betreft voldoende houvast voor een eerste versie van het rapport
