### ISSUE TITLE
Provider testen, Authorisatie

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#54]
# Taak

De test-voorziening moet zich kunnen identificeren bij de provider (JWT token)

[assign aan teamlid]

**Comment by HenriKorver** [comment]
@alextreme Kun jij dit reviewen?

**Comment by alextreme** [comment]
Zeker, dit zou inmiddels goed moeten staan. Ik wacht de update van test & staging af en laat Alvise eerst zijn nieuwe collections invoeren en controleren, morgen ga ik er zelf even doorheen.

**Comment by alextreme** [comment]
We hebben hier nog wat slagen in moeten maken, dit omdat eerdere postman collections nog de authentication header overschreven en de Client ID en Secret nog niet werden gebruikt voor het genereren van een JWT token.

Dit werkt nu naar behoren, we hebben op vng-staging nu een test-scenario toegevoegd waarbij de JWT-token correct moet zijn ("ZDS 2.0 verification test (JWT auth required)"). Dit geeft zoals je zou verwachten 403's wanneer de Client ID en Secret niet kloppen.

Daarnaast hebben we de authenticatie-middelen uitgebreid voor de test scenario's met opties voor 'Authorization header' en 'No auth'. Dit zorgt ervoor dat we andere soorten API's waarbij geen JWT-authorisatie wordt gebruikt (Tokens of geen authorisatie) ook kunnen testen via het test-platform.
