### ISSUE TITLE
ZGW Demo feedback 31/01 

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#62]
**Feedback naar aanleiding van @HenriKorver 's demo vandaag van de api-testvoorziening**

Onderdeel: Test-client
- Volgorde van nieuwe sessies - dit gaat wel goed via de API van de testsessions, maar niet via de webinterface. -> doorgevoerd en klaar om na de update van vng-test te hertesten
- Rapport-calls worden nog niet samengevoegd (was al eerder aangekaart). Zie ter voorbeeld https://vng-test.maykin.nl/359/report (met user: henri) -> door te geven aan Alvise
- Matching-algorithme voor de rapporten mag verbreed worden:
  - Gebruik van 'ster' notatie om delen van een URL te matchen. Concreet voorbeeld in ZRC: '/api/v1/zaken/<uuid-zaak>/informatieobjecten', dit zou met een Scenario case als '/api/v1/zaken/*/informatieobjecten' gevangen kunnen worden.
- Het stoppen van een sessie blijkt niet altijd mogelijk -> status werd niet correct opgeslagen, klaar om na de update van vng-test te hertesten
- 'Postman' kolom in de lijstweergave van de sessies dient te worden verwijderd. -> door te geven aan Alvise
- Proxy API - 'Content type' meegeven van de responses, dit zodat je via de Proxy URLs kan zien wat er wordt teruggekeerd.

**Comment by alextreme** [comment]
@HenriKorver het eerste punt is verholpen op vng-test.

De overige 5 punten worden volgende week opgepakt

**Comment by HenriKorver** [comment]
@Joeri Heeft Alvise deze punten al opgepakt?

**Comment by joeri** [comment]
Ik denk dat je iemand anders voor hebt.

**Comment by HenriKorver** [comment]
Sorry ik bedoelde @joeribekker

**Comment by alextreme** [comment]
Feedback is inmiddels doorgevoerd en gecontroleerd.

Enige opmerking is dat de wildcard's expliciet een variabele-naam gegeven moeten worden, bijvoorbeeld:

https://vng-staging.maykin.nl/admin/testsession/scenariocase/?vng_endpoint__session_type__id__exact=6

/test/{uuid}/end

Dit leek ons een overzichtelijkere manier (en hiermee houden we de deur open voor extra validatie van deze variabelen). We hebben een help-text toegevoegd aan de admin met een voorbeeld hiervoor.
