### ISSUE TITLE
Provider Demo API installeren 

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#67]
Demo API installeren zodat PO zonder afhankelijkheid aan ZGW het ATV kan demonstreren.

Joeri heeft een Demo API ontwikkeld met Alvise, en Alvise heeft hier (lokaal) een reeks Postman's opgezet. Hiermee valt de 'Test Provider' deel van het testplatform te demonstreren.

**Toelichting**:
De verwachting is een stabiele API waarmee het testplatform getest kan worden. De omgeving dient niet op een productieomgeving ingericht te worden.

**Oplossingsrichting**:

**Definition of ready**
- [x] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/3 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)

**Comment by alextreme** [comment]
Joeri heeft aangeboden dit voor ons te doen <3

**Comment by joeribekker** [comment]
Kijkt u eens: https://ref.tst.vng.cloud/demo-api/api/v2/schema/

Voorbeeld:
https://ref.tst.vng.cloud/demo-api/api/v2/quotes/893f31c2-8a69-4063-bb41-cb54804ccf28

**Comment by alextreme** [comment]
Demo API is beschikbaar en werkt zoals verwacht.

Ik sluit deze issue, ik laat Alvise nog wel de vng-staging ATV uitbreiden met een Provider test voor deze API
