### ISSUE TITLE
Als beheerder van de testvoorziening wil ik dat nieuwe gebruikers zich zelf kunnen registreren

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#71]
zodat deze gebruikers zonder tussenkomst van een beheerder/admin meteen gebruik kunnen maken van de testvoorziening.

**Toelichting**:
Het spreekt voor zich dat nieuwe gebruikers zich snel en gemakkelijk moeten kunnen aanmelden.

**Oplossingsrichting**:
Nieuwe gebruiker laten registreren door middel van emailvalidatie. Bovendien checken dat de aanmelder geen robot is.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by HenriKorver** [comment]
Ter inspiratie. Auth0 biedt authentication as service. Ik heb er geen ervaring mee maar het ziet erg goed uit:
https://auth0.com/resources/videos/auth0-developer-overview

**Comment by HenriKorver** [comment]
Auth0 is een mooie dienst maar wel commercieel. Er is ook een interessante open source ontwikkeling: https://www.keycloak.org/

https://en.wikipedia.org/wiki/List_of_single_sign-on_implementations geeft een interessant beeld van andere oplossingen. ook open source...

**Comment by alextreme** [comment]
Single Sign-on is geen onderdeel van deze user story. Het kan allemaal wel, maar je opmerkingen zijn in mijn ogen out-of-scope.

**Comment by HenriKorver** [comment]
> Single Sign-on is geen onderdeel van deze user story. Het kan allemaal wel, maar je opmerkingen zijn in mijn ogen out-of-scope.

Eens. Daarom heb ik een nieuwe user story aangemaakt (#96) die we mogelijk in een latere sprint kunnen oppakken.

**Comment by alextreme** [comment]
Beschikbaar op vng-test en vng-staging. Ik loop vanmiddag nog even de Nederlandse teksten langs

**Comment by alextreme** [comment]
@HenriKorver graag je review voor het registratieproces op vng-staging.maykin.nl ( https://vng-staging.maykin.nl/accounts/register/ ).

Het werkt inmiddels naar mijn idee goed (en we hebben de recaptcha keys nu 'productiewaardig' gemaakt), ik heb nog wat laatste vertaal-verzoeken naar Alvise gestuurd maar ik combineer dit graag met eventuele wensen / tekstuele uitbreidingen/uitleg van jouw kant.

**Comment by HenriKorver** [comment]
@AlviseSembenico @alextreme No I did not succeed in registering. For instance I tried to register as user puk75 but did not get a confirmation email.

**Comment by alextreme** [comment]
Thanks, I'll investigate if the email was accepted as it was sent from a valid emailadres (test at maykinmedia dot nl)

**Comment by alextreme** [comment]
Outlook/Exchange is being troublesome unfortunately, it has banned the server vng-staging is on:

2019-04-09 10:27:03 1hDny2-0002vW-Qz ** <henri's emailadres> l R=dnslookup T=remote_smtp H=vng-nl.mail.protection.outlook.com [104.47.10.36] X=TLS1.2:ECDHE_RSA_AES_256_GCM_SHA384:256 CV=yes DN="C=US,ST=Washington,L=Redmond,O=Microsoft Corporation,CN=mail.protection.outlook.com": SMTP error from remote mail server after RCPT TO:<henri's emailadres>: 550 5.7.606 Access denied, banned sending IP [81.171.12.59]. To request removal from this list please visit https://sender.office.com/ and follow the directions. For more information please go to  http://go.microsoft.com/fwlink/?LinkID=526655 (AS16012609) [DB5EUR03FT010.eop-EUR03.prod.protection.outlook.com]

**Comment by alextreme** [comment]
@HenriKorver I've sent you a delisting email via Microsoft's service, this will ensure the test-environment is allowed to send you emails again (I suspect it was blocked after we tried to do this a few times with @example.com as a sender).

If this doesn't work I'll hook up a third-party SMTP service (Sendgrid) to the test and staging environments.

**Comment by HenriKorver** [comment]
A minute ago I tried to register as pukman1,  but still have not received a confirmation mail

**Comment by alextreme** [comment]
@HenriKorver the mail was blocked. Have you followed the delisting email instructions?

**Comment by HenriKorver** [comment]
I tried to follow the delisting instructions but there also I have to wait on a confirmation email which does not arrive.

![afbeelding](https://user-images.githubusercontent.com/37145898/55828677-41e8f780-5b0d-11e9-8157-5ab326a2a70f.png)

**Comment by alextreme** [comment]
@AlviseSembenico I've modified the test + staging settings to send email via Sendgrid after the next deploy.

**Comment by alextreme** [comment]
@HenriKorver Emails from test and staging are now being sent via Sendgrid. I just did a registration with your emailadres on staging and it appears to have been delivered properly:

![Screenshot_2019-04-11_16-18-29](https://user-images.githubusercontent.com/226839/55964773-9313fb00-5c75-11e9-96a7-968c0135d17a.png)

**Comment by HenriKorver** [comment]
Unfortunately nothing received by mail. Just tried to add two new users:
* jand (vng mail account)
* donaldduck (private email account)

No succes, no confirmation email arrived

**Comment by alextreme** [comment]
@HenriKorver have you checked your spamfolder? Both emails were delivered this morning as far as Sendgrid knows:

![Screenshot_2019-04-12_14-37-21](https://user-images.githubusercontent.com/226839/56037820-8f917a00-5d30-11e9-882b-838b9b45334f.png)

**Comment by HenriKorver** [comment]
In de spamfolder of my private account I found the confirmation mail and succeeded in registering user donalduck. However I did not find a mail for user jand in my vng spam folder

**Comment by alextreme** [comment]
@HenriKorver Could we make use of the VNG-R mailserver for sending out email, or contact someone about sending/receiving email to vng.nl? 

We can put further effort into getting the emails delivered properly to your address, however if the end-goal is sending out email as (for instance) testplatform@vng.nl it might make more sense to do this instead.

**Comment by HenriKorver** [comment]
@melsk-r @michielverhoef Do you know who to contact for using the mailserver of VNG-R?

**Comment by michielverhoef** [comment]
Unfortunately I do not have this information. The best option would be to contact Valid supportdesk as they are the maintainers of the mailserver of VNG.

**Comment by alextreme** [comment]
Henri will contact support and mention what he needs, for further assistance I'll be available to discuss this with them

**Comment by HenriKorver** [comment]
I have just contacted the VNG ICT helpdesk and they solved the problem by removing test@maykinmedia.nl (the sender-address of the verification email for completing the registration at th ATP) from the blacklist
