### ISSUE TITLE
Kan geen scenario case koppelen aan een session type in admin

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#73]
![image](https://user-images.githubusercontent.com/37145898/53686128-a7ceac00-3d23-11e9-8f66-9edbf5a5b96a.png)

**Comment by alextreme** [comment]
Dit is gewoon mogelijk via het toevoegen/wijzigen van een scenario case.

Waar je waarschijnlijk tegenaan liep was dat je een endpoint moest selecteren in plaats van een session type. Dit is nodig aangezien we de scenario-controle per endpoint doen (voorbeeld: een POST op zaken is correct voor ZRC, maar onjuist voor het ZTC).

Ik heb de naamgeving van de endpoint verduidelijkt met de naam van de sessie-type erachter:

![screenshot_2019-03-04_11-20-19](https://user-images.githubusercontent.com/226839/53727160-d2c61680-3e6f-11e9-88d5-c092c77782e7.png)

**Comment by HenriKorver** [comment]
@alextreme Weet niet of dit juiste weg is. Door deze verandering moet ik de javascriptcode in mijn Postman collections aanpassen.
Bovendien is het vreemd dat de definitie van vng end-point nu verweven is met een session type.

**Comment by alextreme** [comment]
Als je een voorstel hebt hoe het anders kan dan hoor ik het graag.

Helaas kan ik ook niet vooraf inschatten of een aanpassing aan het test-platform qua naamgeving voor wijzigingen in je collections zal zorgen.

**Comment by alextreme** [comment]
Bij deze heeft Alvise mijn aanpassing doorgevoerd zodat je bij de scenario-cases je endpoints uit elkaar kan houden, maar hij heeft dit beter gedaan zodat dit niet tot API veranderingen leidt.

Ter controle

**Comment by HenriKorver** [comment]
Ja werkt nu goed
