### ISSUE TITLE
API testplatform VNG-R ondersteunt agile inbouwen van ZGW API

### ISSUE THREAD

**Issue by andyverberne** [VNG-Realisatie/api-testvoorziening#74]
Als ontwikkelaar wil ik de ZGW API agile inbouwen in mijn applicatie. Ik wil niet in een keer de volledige ZGW API realiseren maar slechts dat deel wat nodig is om te kunnen koppelen met specifieke andere applicaties. Doel is om zo snel mogelijk een koppeling te kunnen realiseren met van te voren geselecteerde andere applicaties. Vaak hoeft bij zo'n koppeling niet de volledige ZGW API te worden ondersteunt.

Dit heeft consequenties voor het API testplatform VNG-R. Het moet namelijk mogelijk zijn om delen van de ZGW API te kunnen valideren tegen de standaard. En het moet vooral niet worden aangemoedigd om een "groen vinkje" te behalen ter bevestiging dat de volledige standaard wordt ondersteund omdat partijen dan te lang wachten met de inbouw en het testen van koppelingen met andere partijen.

**Comment by alextreme** [comment]
Zowel het testen van een deel van een consumer als een deel van een provider is voorzien, dus ik zie het gemelde niet als een issue.

Aan Henri als PO om dit te bevestigen of om hier een actionable user story van te maken.

**Comment by HenriKorver** [comment]
@andyverberne Bedankt voor je vraag. Eens met @alextreme het sowieso al mogelijk is om consumers of providers gedeeltelijk te kunnen testen. Jouw vraag houdt meer verband met vormgeving en interpretatie van de testrapporten en badges voor compliancy doeleinden. Daar moet nog over nagedacht worden. Uiteindelijk moet het duidelijk zijn  wanneer een leverancier volledig, gedeeltelijk of niet voldoet aan de standaard.
Voor dit verhaal is al een US aangemaakt (zie #4) en daarom sluit ik deze.
