### ISSUE TITLE
Herschrijven URLs werkt nog niet goed bij de root URLs

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#75]
Probeer bijvoorbeeld deze URL:
https://vng-test.maykin.nl/runtest/154999490370/ZRC/

Ten eerste heeft de resulterende pagina zijn opmaak verloren. Ten tweede werken de links daar niet meer.

![afbeelding](https://user-images.githubusercontent.com/37145898/53946558-5d06b880-40c4-11e9-8d4f-fe0579aab28e.png)

**Comment by alextreme** [comment]
Dit heeft te maken met absolute paden, zoals verwijzigingen naar een logo:
/static/logo.png

Dit wordt herschreven via de proxy naar:

https://vng-test.maykin.nl/static/logo.png

Zo verloopt de URL buiten de proxy om.

Een mogelijke oplossing hiervoor zou zijn om een subdomein per testsessie te hebben:

https://runtest123.vng-test.maykin.nl/static/logo.png

Dit zou ervoor zorgen dat we alsnog een match kunnen maken via de proxy, ook voor verwijzingen naar de 'root' van het domein.

**Comment by alextreme** [comment]
Alvise is aan het uitzoeken wat ervoor nodig is om een subdomeinen per sessie aan te maken

**Comment by alextreme** [comment]
Op de test-omgeving is dit nu doorgevoerd, gaan we nog eerst even verder testen
