### ISSUE TITLE
Totale resultaat van een test wordt nog niet goed uitgedrukt

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#76]
Het eerst result veld in onderstaande response zou "gedeeltelijk succesvol" moeten zijn in plaats van "failed". 

```
{
    "test_session_url": "https://vng-staging.maykin.nl/617/",
    "result": "failed",
    "report": [
        {
            "result": "Succesvol",
            "scenario_case": {
                "url": "/api/v1/zaken",
                "http_method": "GET",
                "vng_endpoint": 9
            }
        },
        {
            "result": "Niet uitgevoerd",
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}",
                "http_method": "PUT",
                "vng_endpoint": 9
            }
        },
        {
            "result": "Niet uitgevoerd",
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}/informatieobjecten",
                "http_method": "GET",
                "vng_endpoint": 9
            }
        },
        {
            "result": "Niet uitgevoerd",
            "scenario_case": {
                "url": "/api/v1/statussen",
                "http_method": "GET",
                "vng_endpoint": 9
            }
        }
    ]
}
```

**Comment by AlviseSembenico** [comment]
The outcome can be seen here
https://vng-staging.maykin.nl/api/v1/testsessions/617/result

`{
    "result": "Gedeeltelijk succesvol",
    "test_session_url": "https://vng-staging.maykin.nl/617/",
    "report": [
        {
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}",
                "http_method": "PUT",
                "vng_endpoint": 9
            },
            "result": "Succesvol"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken",
                "http_method": "GET",
                "vng_endpoint": 9
            },
            "result": "Succesvol"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}/informatieobjecten",
                "http_method": "GET",
                "vng_endpoint": 9
            },
            "result": "Succesvol"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken",
                "http_method": "POST",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken/_zoek",
                "http_method": "POST",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}",
                "http_method": "GET",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        },
        {
            "scenario_case": {
                "url": "/api/v1/statussen",
                "http_method": "GET",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}",
                "http_method": "DELETE",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}/informatieobjecten",
                "http_method": "POST",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}/zaakeigenschappen",
                "http_method": "GET",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        },
        {
            "scenario_case": {
                "url": "/api/v1/zaken/{uuid}/zaakeigenschappen",
                "http_method": "POST",
                "vng_endpoint": 9
            },
            "result": "Niet uitgevoerd"
        }
    ]
}`
