### ISSUE TITLE
Scenario cases staan niet in de goede volgorde

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#77]
Onderstaande  scenario cases staan niet in dezelfde volgorde zoals gespecificeerd in de Admin module:

![afbeelding](https://user-images.githubusercontent.com/37145898/53953664-2e90d980-40d4-11e9-92ee-96543e36518d.png)

**Comment by HenriKorver** [comment]
![afbeelding](https://user-images.githubusercontent.com/37145898/53970018-277cc200-40fa-11e9-8fc3-007dda885f4c.png)

**Comment by alextreme** [comment]
Bug ijkt verholpen op vng-staging met testsessie #619. Mag nog wel voor de zekerheid worden bevestigd aangezien in deze issue geen testsessie-nummer is bijgesloten (anders had ik bij je testsessie kunnen meekijken)

**Comment by HenriKorver** [comment]
Ja het werkt nu goed
