### ISSUE TITLE
Als testcoördinator (leverancier) wil ik alle configuratie via een api kunnen doen én via een webinterface

### ISSUE THREAD

**Issue by TCIMEddy** [VNG-Realisatie/api-testvoorziening#8]
zodat....(altijd beschrijven!)

**Toelichting**:
...

**Oplossingsrichting**:
...

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done**
- [ ] Prototype (indien niet van toepassing afvinken)
- [ ] Funcitionele specificatie
- [ ] Technische specificatie
- [ ] Non functionals (eisen/specificatie)
- [ ] Documentatie bijgewerkt

**Acceptatiecriteria**
- [ ] Ook voor beheer is het van belang dat een testcoördinator dit zelf kan en beheer hier zo min mogelijk vragen over krijgt.
- [ ] ...
- [ ] ...

**Taken**
- [ ] ...
- [ ] ...
- [ ] ...
- [ ] ...

**Comment by melsk-r** [comment]
Ook voor beheer is het van belang dat een testcoördinator dit zelf kan en beheer hier zo min mogelijk vragen over krijgt.

**Comment by TCIMEddy** [comment]
@melsk-r acceptatiecriterium dus neem hem hier ook in op. Heb ik nu gedaan
