### ISSUE TITLE
Als deelnemer van een workshop wil ik voldoende documentatie hebben 

### ISSUE THREAD

**Issue by JanWillemKooi** [VNG-Realisatie/api-testvoorziening#80]
...zodat ik eenvoudig aan de slag kan gaan met de API-testvoorziening.

**Toelichting**:
We willen tijdens de API-lab van ZGW een workshop geven over de API-testvoorziening. Daarvoor moet voldoende documentatie aanwezig zijn op GitHub. 

**Oplossingsrichting**:
Op GitHub een documentje (1 of enkele A4's) met een stappenplan hoe je de API-testvoorziening kan gebruiken. Bijvoorbeeld een uitwerking met Postman zodat de populariteit van het gebruik van Postman wordt getest. 

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [x] Is klein genoeg (maximaal 1/3 van sprint)
- [x] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [x] Voorzien van Definition of Done (duidelijk en testbaar)

- [x] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [x] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done specifiek voor deze user story**
- [ ] Bruikbaar voor de workshop waarbij we nuttige feedback krijgen.

**Acceptatiecriteria**
- [ ] Vlot leesbaar in nederlands
- [ ] Met Screenshots zodat mensen al doende begrijpen hoe de tooling werkt
- [ ] ...

**Taken**
-[ ] Voordbeeld van wat wordt bedoeld

**Comment by HenriKorver** [comment]
Voorbeeldje van hoe bij het ZGW API Lab ging:
https://ref.tst.vng.cloud/ontwikkelaars/aan-de-slag
