### ISSUE TITLE
Opschonen files in de Code repository

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#81]
# Scrumtaak

Op het root niveau van de file repository staan te veel files waardoor het geheel een beetje onoverzichtelijk is geworden. Graag deze files opschonen of verhuizen naar andere folders.

**Comment by alextreme** [comment]
Een reeks onnodige bestanden zijn verwijderd:

https://github.com/maykinmedia/api-testvoorziening/commit/9416ae210bef01c84225801f345f55e479943bca

Als je meer bestanden wilt weggooien dan graag aangeven welke. We hebben namelijk vrij veel tooling in place wat inhaakt op bestanden in de project-directory.

**Comment by HenriKorver** [comment]
Ik kan niet goed zien wat het eindresultaat zal zijn van deze opschoning na de merge, maar wat ik bedoel is dat de bestanden tussen de `src` folder en de `README.md` verhuisd moeten worden naar een folder.
![afbeelding](https://user-images.githubusercontent.com/37145898/54430347-92924e00-4723-11e9-9723-dab8db18ef6f.png)

**Comment by alextreme** [comment]
Een deel hiervan wordt gewist bij de volgende merge.
De rest blijft staan, deze zijn noodzakelijk voor ons om het project te kunnen starten/controleren

**Comment by HenriKorver** [comment]
Maar ik zie nog geen pull request voor de volgende merge?
