### ISSUE TITLE
Lukt niet om via API resultaat op te vragen van een provider run

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#84]
# Bug
`GET https://vng-staging.maykin.nl/api/v1/provider-run/77/result`
geeft een 500 error

De vraag is waarom het resultaat niet wordt teruggegeven door middel van deze request (zonder de sub resource `result`)

`GET https://vng-staging.maykin.nl/api/v1/provider-run/77`

```json
{
    "id": 77,
    "test_scenario": "ZDS 2.0 verification test",
    "started": "2019-03-09T12:29:03.405517+01:00",
    "stopped": "2019-03-09T12:29:09.760261+01:00",
    "client_id": "tj",
    "secret": "tyj",
    "endpoints": [
        {
            "url": "https://ref.tst.vng.cloud/drc/",
            "test_scenario_url": {
                "name": "DRC"
            }
        },
        {
            "url": "https://ref.tst.vng.cloud/ztc/",
            "test_scenario_url": {
                "name": "ZTC"
            }
        },
        {
            "url": "https://ref.tst.vng.cloud/zrc/",
            "test_scenario_url": {
                "name": "ZRC"
            }
        }
    ],
    "status": "stopped"
}
```
Naast het feit dat de provider-run gestopt is wil je natuurlijk ook weten of ie wel of niet geslaagd is.  Als je die informatie hier opneemt dan is de operatie `provider-run/{id}/result` niet meer nodig.

Onderstaand user interface is bovendien verwarrend omdat de term status zowel voorkomt in de eerste kolom op rij-niveau en in de derde kolom als header. Het is ook niet duidelijk wat de toegevoegde waarde is van de lege kolom Action.

![afbeelding](https://user-images.githubusercontent.com/37145898/54071378-1784ef80-426c-11e9-8f21-51d89ee882be.png)

**Comment by alextreme** [comment]
De bug is duidelijk (ik had het donderdag al gezien en aan Alvise toegewezen).

Echter deze issue bevat ook verbeteringen, dus graag slicen voordat je het in de sprint opneemt.

**Comment by alextreme** [comment]
Hiervoor is op vng-test een oplossing voor doorgevoerd. Graag je goedkeuring, dan voeren we dit door naar vng-staging

**Comment by HenriKorver** [comment]
Bij deze mijn goedkeuring. Kan ik dit issue sluiten? Of eerst wachten totdat het is doorgevoerd naar staging?

**Comment by alextreme** [comment]
Bij deze is de aanpassing ook doorgevoerd naar staging, wees vrij om het te sluiten.
