### ISSUE TITLE
API call voor creeren consumer testsessie met docker container gaat niet goed

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#85]
# Bug
```
POST https://vng-staging.maykin.nl/api/v1/testsessions/
{
	"session_type": "Demo API test (Docker)"
}
```
geeft het volgende terug

```
{
    "id": 635,
    "session_type": "Demo API test (Docker)",
    "started": "2019-03-11T12:22:16.650204+01:00",
    "stopped": null,
    "status": "starting",
    "exposedurl_set": [],
    "build_version": null
}
```

Helaas is de exposedurl_set leeg. Bovendien verschijnt sessie 635 niet in het user interface,

**Comment by alextreme** [comment]
Afgelopen donderdag bevestigd, Alvise gaat hier naar kijken.

We vermoeden (omdat het wel via de webinterface werkt) dat het ligt aan het feit dat we deze API call blocking hebben gemaakt, wellicht dat er ergens een timeout optreedt en dat je het resultaat terug krijgt voordat de testsessie daadwerkelijk kon worden gestart.

**Comment by alextreme** [comment]
Dit moet zoals in #18 aangegeven veranderd worden in je Postman collection, aangezien de status van je sessie 'running' moet zijn voordat je sessie bruikbaar is. Het is echter geen bug in het testplatform.

**Comment by alextreme** [comment]
Alvise:
I added the postman collection as example, it can be accomplished easily with the following lines:
var jsonData = pm.response.json();
if(jsonData.status != "running"){
      postman.setNextRequest("<REQUESTNAME>")
}
Where the request name is the name of the postman tab

**Comment by HenriKorver** [comment]
@AlviseSembenico @alextreme Could you provide me with the postman collection?

**Comment by HenriKorver** [comment]
By the way I am reviewing this functionality on de staging server (https://vng-staging.maykin.nl/). Is that what you want?
Because I can't login into the testing server (https://vng-tst.maykin.nl)...

**Comment by alextreme** [comment]
the domain for the test-environment is https://vng-test.maykin.nl.
We'll provide you with an example on monday

**Comment by HenriKorver** [comment]
These issue seems related with #95

**Comment by alextreme** [comment]
Hier het voorbeeld van Alvise

[testsessionpostman_collection_awaiting.txt](https://github.com/VNG-Realisatie/api-testvoorziening/files/2980392/testsessionpostman_collection_awaiting.txt)
