### ISSUE TITLE
Test consumer - Mogelijk maken dat per session type de authentication door een beheerder ingevuld kan worden

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#90]
zodat het eenvoudiger wordt om met de APIs aan de slag te gaan.

**Toelichting**:
...

**Oplossingsrichting**:

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by JanWillemKooi** [comment]
@HenriKorver gaat deze US verduidelijken.
@alextreme  gaat nadenken over mogelijke oplossingen samen met @AlviseSembenico

**Comment by alextreme** [comment]
How this could be implemented is by adding optional Client ID and Secret fields to the Consumer SessionType. This would allow the test platform to generate a JWT token on-the-fly when starting the consumer session

When a Proxy call comes in via the test platform the test platform would check if an Authentication header is given. If not, the test platform would then add the JWT Authentication header for every call that comes in.

**Comment by HenriKorver** [comment]
Deze is dubbel met #86 en daarom sluit ik dit issue
