### ISSUE TITLE
Consumer test sessions with docker do not work on https://vng-staging.maykin.nl/

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#95]
# Bug
After about 20 seconds session  677 disappears from the list
![afbeelding](https://user-images.githubusercontent.com/37145898/54436823-8dd59600-4733-11e9-80b6-9d3b44dd94e3.png)

![afbeelding](https://user-images.githubusercontent.com/37145898/54436919-ce351400-4733-11e9-861e-e87e5ff5e3ff.png)

**Comment by alextreme** [comment]
It seems there are too many workloads active at the same time:
"0/3 nodes are available: 3 Insufficient cpu."
![Screenshot_2019-03-15_15-27-43](https://user-images.githubusercontent.com/226839/54438487-00944080-4737-11e9-89ca-eb5b324acd21.png)

https://cloud.google.com/kubernetes-engine/docs/troubleshooting?hl=en_US&_ga=2.48876452.-328591515.1486376270#PodUnschedulable

**Comment by HenriKorver** [comment]
Wat nu?

**Comment by alextreme** [comment]
I've deleted the 20 active workloads. I suspect we'll have to set up some kind of auto-termination of testsessions.

**Comment by alextreme** [comment]
https://github.com/maykinmedia/api-testvoorziening/pull/66

**Comment by alextreme** [comment]
Geimplementeerd en beschikbaar op vng-test. Voeren we maandag a.s. door naar vng-staging

**Comment by HenriKorver** [comment]
Opgelost
