### ISSUE TITLE
As a consumer-tester I do not want to wait on the creation process of a docker-container in the Kubernetes environment

### ISSUE THREAD

**Issue by HenriKorver** [VNG-Realisatie/api-testvoorziening#97]
such that I do not lose my patience

**Toelichting**:
...

**Oplossingsrichting**:
Taking care that there are always a few docker-containers started in advance.

**Definition of ready**
- [ ] Iedereen in het team begrijpt de user story
- [ ] Is klein genoeg (maximaal 1/3 van sprint)
- [ ] Product Owner akkoord en voorzien van prioriteit (mag alleen afgevinkt worden door Henri)
- [ ] Voorzien van Acceptatiecriteria (duidelijk en testbaar)
- [ ] Voorzien van Definition of Done (duidelijk en testbaar)
- [ ] Voorzien van taken
- [ ] Idee hebben van hoe deze user story kan worden gedemonstreerd.
- [ ] Vastgelegd in Github en geplaatst in kolom ready

**Definition of done algemeen**
- [ ] Tekst Aanbesteding

**Definition of done specifiek voor deze user story**
- [ ] ....

**Acceptatiecriteria**
- [ ] ...
- [ ] ...
- [ ] ...

**Taken**
Taken worden apart uitgewerkt in issues.

**Comment by alextreme** [comment]
Lets discuss what is possible, this may become quite complicated but I understand that the 1-2 minute start time is too long.

**Comment by alextreme** [comment]
As discussed Alvise has added a progress-bar to these sessions on vng-test. We'll update vng-staging on monday with this.

However as this is more a workaround than an implementation of this user story I'll keep this in 'Ready for sprint' for now.

**Comment by HenriKorver** [comment]
The progress-bar is a perfect solution
