### ISSUE TITLE
Give Alvise write-access to the github repository

### ISSUE THREAD

**Issue by alextreme** [VNG-Realisatie/api-testvoorziening#99]
# Scrumtaak

[beschrijf de scrumtaak]

[assign aan teamlid en voeg label 'scrumtaak' toe]

**Comment by HenriKorver** [comment]
As far as my knowledge reaches @AlviseSembenico  already has write-acces. Please confirm before I close this issue!

**Comment by HenriKorver** [comment]
@alextreme and  @AlviseSembenico please react!

**Comment by AlviseSembenico** [comment]
@HenriKorver Yes, I have the write rights, you can close it. Thanks
